/** Generated from source/tokens.mjs. Do not edit manually. */
export const tokenValues = {
  "typography.fontFamily": "Inter, ui-sans-serif, system-ui, sans-serif",
  "typography.fontSize.sm": "0.875rem",
  "typography.fontSize.md": "1rem",
  "typography.fontSize.lg": "1.125rem",
  "typography.fontWeight.regular": "400",
  "typography.fontWeight.medium": "500",
  "typography.fontWeight.semibold": "600",
  "typography.lineHeight.normal": "1.5",
  "typography.lineHeight.tight": "1.25",
  "spacing.1": "0.25rem",
  "spacing.2": "0.5rem",
  "spacing.3": "0.75rem",
  "spacing.4": "1rem",
  "spacing.6": "1.5rem",
  "spacing.8": "2rem",
  "dimension.controlSm": "2rem",
  "dimension.controlMd": "2.5rem",
  "dimension.controlLg": "3rem",
  "border.width": "1px",
  "radius.sm": "0.25rem",
  "radius.md": "0.5rem",
  "radius.lg": "0.75rem",
  "radius.full": "9999px",
  "elevation.sm": "0 1px 2px rgb(15 23 42 / 0.08)",
  "elevation.md": "0 8px 24px rgb(15 23 42 / 0.12)",
  "opacity.disabled": "0.5",
  "opacity.overlay": "0.64",
  "motion.fast": "120ms",
  "motion.normal": "180ms",
  "motion.easing": "cubic-bezier(0.2, 0, 0, 1)",
  "color.background": "#f8fafc",
  "color.surface": "#ffffff",
  "color.surfaceRaised": "#ffffff",
  "color.text": "#0f172a",
  "color.textMuted": "#64748b",
  "color.border": "#e2e8f0",
  "color.primary": "#2563eb",
  "color.primaryHover": "#1d4ed8",
  "color.success": "#10b981",
  "color.warning": "#f59e0b",
  "color.danger": "#ef4444",
  "color.onPrimary": "#ffffff"
} as const
export type TokenName = keyof typeof tokenValues
export const tokenCssVariable = (name: TokenName) => `--ads-${name.replaceAll(".", "-").replaceAll(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)}`
