/** Generated from source/tokens.mjs. Do not edit manually. */
export const tokenValues = {
  "typography.fontFamily": "Inter, Roboto, sans-serif",
  "typography.fontSize.xs": "0.75rem",
  "typography.fontSize.sm": "0.875rem",
  "typography.fontSize.md": "1rem",
  "typography.fontSize.lg": "1.125rem",
  "typography.fontSize.xl": "1.25rem",
  "typography.fontSize.2xl": "1.5rem",
  "typography.fontSize.3xl": "1.875rem",
  "typography.fontSize.4xl": "2.25rem",
  "typography.fontWeight.regular": "400",
  "typography.fontWeight.medium": "500",
  "typography.fontWeight.semibold": "600",
  "typography.fontWeight.bold": "700",
  "typography.lineHeight.normal": "1.5",
  "typography.lineHeight.interface": "1.4",
  "typography.lineHeight.tight": "1.25",
  "typography.lineHeight.heading": "1.2",
  "spacing.1": "0.25rem",
  "spacing.2": "0.5rem",
  "spacing.3": "0.75rem",
  "spacing.4": "1rem",
  "spacing.6": "1.5rem",
  "spacing.8": "2rem",
  "dimension.controlSm": "2rem",
  "dimension.controlMd": "2.25rem",
  "dimension.controlLg": "2.5rem",
  "dimension.fieldSm": "1.75rem",
  "dimension.fieldMd": "2rem",
  "dimension.fieldLg": "2.25rem",
  "border.width": "1px",
  "radius.sm": "0.375rem",
  "radius.md": "0.375rem",
  "radius.lg": "0.5rem",
  "radius.full": "9999px",
  "elevation.sm": "0 1px 2px rgb(15 23 42 / 0.08)",
  "elevation.md": "0 8px 24px rgb(15 23 42 / 0.12)",
  "opacity.disabled": "0.5",
  "opacity.overlay": "0.64",
  "motion.fast": "120ms",
  "motion.normal": "180ms",
  "motion.easing": "cubic-bezier(0.2, 0, 0, 1)",
  "color.background": "#f8fafc",
  "color.canvas": "#f8fafc",
  "color.surface": "#ffffff",
  "color.surfaceRaised": "#ffffff",
  "color.surfaceMuted": "#f1f5f9",
  "color.text": "#0f172a",
  "color.textPrimary": "#0f172a",
  "color.textMuted": "#475569",
  "color.textSecondary": "#475569",
  "color.border": "#e2e8f0",
  "color.primary": "#2563eb",
  "color.primaryHover": "#1d4ed8",
  "color.focus": "#2563eb",
  "color.info": "#0369a1",
  "color.success": "#15803d",
  "color.warning": "#b45309",
  "color.danger": "#b91c1c",
  "color.onPrimary": "#ffffff",
  "color.formBackground": "#ffffff",
  "color.formBackgroundDisabled": "#f1f5f9",
  "color.formBorderFocus": "#2563eb",
  "color.formInvalid": "#b91c1c",
  "color.formSuccess": "#15803d",
  "color.successBackground": "#f0fdf4",
  "color.warningBackground": "#fffbeb",
  "color.dangerBackground": "#fef2f2",
  "color.infoBackground": "#f0f9ff",
  "color.successBorder": "#bbf7d0",
  "color.warningBorder": "#fde68a",
  "color.dangerBorder": "#fecaca",
  "color.infoBorder": "#bae6fd",
  "color.overlayBackdrop": "rgb(15 23 42 / 0.64)"
} as const
export type TokenName = keyof typeof tokenValues
export const tokenCssVariable = (name: TokenName) => `--ads-${name.replaceAll(".", "-").replaceAll(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)}`
