export const requiredCategories = [
	'color',
	'typography',
	'spacing',
	'dimension',
	'border',
	'radius',
	'elevation',
	'opacity',
	'motion',
];

export const tokenSource = {
	color: {
		reference: {
			blue500: '#2563eb',
			blue600: '#1d4ed8',
			slate50: '#f8fafc',
			slate100: '#f1f5f9',
			slate200: '#e2e8f0',
			slate500: '#64748b',
			slate700: '#334155',
			slate900: '#0f172a',
			white: '#ffffff',
			emerald500: '#10b981',
			amber500: '#f59e0b',
			red500: '#ef4444',
		},
		semantic: {
			light: {
				background: '{color.reference.slate50}',
				surface: '{color.reference.white}',
				surfaceRaised: '{color.reference.white}',
				text: '{color.reference.slate900}',
				textMuted: '{color.reference.slate500}',
				border: '{color.reference.slate200}',
				primary: '{color.reference.blue500}',
				primaryHover: '{color.reference.blue600}',
				success: '{color.reference.emerald500}',
				warning: '{color.reference.amber500}',
				danger: '{color.reference.red500}',
				onPrimary: '{color.reference.white}',
			},
			dark: {
				background: '{color.reference.slate900}',
				surface: '{color.reference.slate700}',
				surfaceRaised: '{color.reference.slate700}',
				text: '{color.reference.slate50}',
				textMuted: '{color.reference.slate200}',
				border: '{color.reference.slate500}',
				primary: '{color.reference.blue500}',
				primaryHover: '{color.reference.blue600}',
				success: '{color.reference.emerald500}',
				warning: '{color.reference.amber500}',
				danger: '{color.reference.red500}',
				onPrimary: '{color.reference.white}',
			},
		},
	},
	typography: {
		fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
		fontSize: { sm: '0.875rem', md: '1rem', lg: '1.125rem' },
		fontWeight: { regular: '400', medium: '500', semibold: '600' },
		lineHeight: { normal: '1.5', tight: '1.25' },
	},
	spacing: { 1: '0.25rem', 2: '0.5rem', 3: '0.75rem', 4: '1rem', 6: '1.5rem', 8: '2rem' },
	dimension: { controlSm: '2rem', controlMd: '2.5rem', controlLg: '3rem' },
	border: { width: '1px' },
	radius: { sm: '0.25rem', md: '0.5rem', lg: '0.75rem', full: '9999px' },
	elevation: { sm: '0 1px 2px rgb(15 23 42 / 0.08)', md: '0 8px 24px rgb(15 23 42 / 0.12)' },
	opacity: { disabled: '0.5', overlay: '0.64' },
	motion: { fast: '120ms', normal: '180ms', easing: 'cubic-bezier(0.2, 0, 0, 1)' },
};
